### ISSUE TITLE
Option to not create a folder for each date

### ISSUE THREAD

**Issue by uwe999** [omnivore-app/obsidian-omnivore#10]
By default the plugin creates a new folder for each day. 
It would be nice to have that turned off and just create the files in the Omnivore folder

**Comment by willasm** [comment]
I agree with this, would be nice to have this as an option in settings.

**Comment by sambody** [comment]
+1. File names are enough for me.

**Comment by willasm** [comment]
I just created a pull request for this that adds an option to toggle the subfolder usage (defaults to true, uses the subfolder).
Also increased the size of the template text area so it is viewable without having to resize the box.

**Comment by sywhb** [comment]
Hey @uwe999 @sambody @willasm, sorry for the late reply.

I have an idea to address this issue and have put up a PR #25
This will allow you to put all the files in the root folder and you just need to config the settings like this
<img width="658" alt="Screenshot 2023-02-22 at 6 49 24 PM" src="https://user-images.githubusercontent.com/12963965/220598760-d01934c4-ff22-42f3-bd96-025e8547d24f.png">

If you'd like to keep the date as the subfolder, you could just set `Omnivore/{{date}}`
<img width="646" alt="Screenshot 2023-02-22 at 6 46 39 PM" src="https://user-images.githubusercontent.com/12963965/220598998-2976cb35-3925-4bcb-8f46-df5abd9e902e.png">

Do you think it caters to your need?

**Comment by sambody** [comment]
Looks good to me. Thanks for that.

**Comment by sywhb** [comment]
Cool. I will merge this

**Comment by sywhb** [comment]
Version `1.0.6` is released to add this feature

**Comment by willasm** [comment]
Thanks, this works perfectly.

**Comment by GmGniap** [comment]
I know the issue is closed. Is it possible to group the folders by `Labels` instead of **date**?
