### ISSUE TITLE
Where does the metadata go?

### ISSUE THREAD

**Issue by notuntoward** [omnivore-app/obsidian-omnivore#109]
In obsidian, I have the article template set to
> ---
> id: {{{id}}}
> title: >
>   {{{title}}}
> {{#author}}
> author: >
>   {{{author}}}
> {{/author}}
> {{#labels.length}}
> tags:
> {{#labels}} - {{{name}}}
> {{/labels}}
> {{/labels.length}}
> date_saved: {{{dateSaved}}}
> {{#datePublished}}
> date_published: {{{datePublished}}}
> {{/datePublished}}
> ---
> 
> # {{{title}}}
> #Omnivore
> 
> [Read on Omnivore]({{{omnivoreUrl}}})
> [Read Original]({{{originalUrl}}})

It seems like date_saved and date_published should be stored in the obsidian markdown page, but it's not there.  Should it be?

**Comment by sywhb** [comment]
Hey @notuntoward , sorry for the late reply.

We have moved out the front matter from the article template and you can easily put `date_saved` and `date_published` in the front matter settings.

<img width="794" alt="Screenshot 2023-12-10 at 11 39 20 AM" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12963965/aaad10d6-2c22-4b74-95f1-96d528f0945b">

**Comment by notuntoward** [comment]
thanks
