### ISSUE TITLE
1.0.1 version number is wrong

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/obsidian-omnivore#11]
As in the title, it still shows 1.0.0 after installation.

**Comment by sywhb** [comment]
Hey @StrollStars, I have bumped the version number to 1.0.1.

You could download the plugin from releases again to verify.

<img width="269" alt="Screenshot 2023-01-31 at 10 34 01 AM" src="https://user-images.githubusercontent.com/12963965/215648148-068bc5aa-2b09-46db-a24b-674dd19950fd.png">

**Comment by StrollStars** [comment]
@sywhb 1.0.2 is right. Thank you.
