### ISSUE TITLE
[FR] Can we import the colour of the highlight? 

### ISSUE THREAD

**Issue by jun6lee** [omnivore-app/obsidian-omnivore#118]
A recent addition on the highlights allows for four colours. It would be nice to be able to capture them.
Aiming for something like I have set up for my book highlights referenced below based on ZANNOTATIONSTYLE

```
{{#if ZANNOTATIONSELECTEDTEXT}}
{{#is ZANNOTATIONSTYLE 5}}
- 🎯 <mark style="background: #C4B3D9;">{{ZANNOTATIONSELECTEDTEXT}}</mark>
{{/is}}
{{#is ZANNOTATIONSTYLE 4}}
- 🎯 <mark style="background: #E6A5AB;">{{ZANNOTATIONSELECTEDTEXT}}</mark>
{{/is}}
{{#is ZANNOTATIONSTYLE 3}}
- 🎯 <mark style="background: #EDD570;">{{ZANNOTATIONSELECTEDTEXT}}</mark>
{{/is}}
{{#is ZANNOTATIONSTYLE 2}}
- 🎯 <mark style="background: #A8BADE;">{{ZANNOTATIONSELECTEDTEXT}}</mark>
{{/is}}
{{#is ZANNOTATIONSTYLE 1}}
- 🎯 <mark style="background: #B0D17F;">{{ZANNOTATIONSELECTEDTEXT}}</mark>
{{/is}}
{{#is ZANNOTATIONSTYLE 0}}
- 🎯 <mark style="background: #FFD9B3;">{{ZANNOTATIONSELECTEDTEXT}}</mark>
{{/is}}
{{/if}}
```

**Comment by caglarongan** [comment]
It is the last and only feature lacking in Omnivore for me to leave raindrop. Good to see colors.
I also use controlled color vocabulary for book/article highlights. And depending on the color, my raindrop/zotero template adds a tag.

But in Omnivore, I have to first highlight and only then I can add a label/tag.
To make it more streamlined, we need a highlight color selector for templating.
Like `if blue > highlight + #followup`

**Comment by sywhb** [comment]
Hey @jun6lee @caglarongan, we have just released a new version of the plugin which will export color name ('red', 'yellow', 'blue' and 'green') of highlights in the note by have `{{color}}` in your highlight template.

**Comment by caglarongan** [comment]
That's nice to hear!
But I can't achieve what I desire with this new option neither, because we can't use `if` with Mustache Templates.

The best I could think was using color names as tags like `#{{color}}` but I don't want to change my *controlled vocabulary* to color names.

**Comment by sywhb** [comment]
Thanks! 

Yeah, I guess the only way to achieve your goal for now is using the color as tags.
