### ISSUE TITLE
Suggest custom filenames

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/obsidian-omnivore#12]
A bit like saving folders, newly created files can be customized with variables like time and title.

**Comment by sywhb** [comment]
<img width="657" alt="Screenshot 2023-03-07 at 2 54 12 PM" src="https://user-images.githubusercontent.com/12963965/223347096-0d009b87-5436-4fc8-bfcd-752f8de2adab.png">

Sorry for the delay. This is the option in the settings so you could customize the filename with `title` and `date`

**Comment by sywhb** [comment]
#30

**Comment by sywhb** [comment]
@StrollStars Sorry, this is something I have been working on in #30 so it's just a preview from my local machine.

I'm hoping this would suffice your need :)

**Comment by StrollStars** [comment]
@sywhb Thanks, it looks like it will do what I need, but if it doesn't solve https://github.com/omnivore-app/omnivore/issues/1837, I wish to support adding 1 on the original date.

**Comment by sywhb** [comment]
Hey @StrollStars, yeah, we display the date in UTC in the reader currently. I will change it to use local time and will update you once i'm done

**Comment by StrollStars** [comment]
@sywhb thank you very much.

**Comment by sywhb** [comment]
Sorry for the long delay but please check out the new version v1.1.0 @StrollStars 

I hope it will fix the issue here

**Comment by StrollStars** [comment]
@sywhb Thank you very much for adding this feature, I think it fully meets the needs. But there is a small flaw, the Folder Date 
Format must be set at the same time to take effect. If someone wants one of the two to have a date and the other to have no date, there is no way. I don't have this need, so I closed this issue, thanks again.
