### ISSUE TITLE
Only highlights are imported but not the whole article

### ISSUE THREAD

**Issue by Karut** [omnivore-app/obsidian-omnivore#129]
New user here :)

With a problem though: only highlights are imported but not the whole article. 

The drop-down option is set accordingly. {{{content}}} or {{content}} do not appear in the template, I if insert either manually in the template nothing it still only imports the title, link the article and the highlights.

Thank you! I look forward to using the plugin!

**Comment by Maheemal** [comment]
```
{{{ content }}}
```

https://docs.omnivore.app/integrations/obsidian.html#importing-the-full-article-content

**Comment by Karut** [comment]
> ```
> {{{ content }}}
> ```
> 
> https://docs.omnivore.app/integrations/obsidian.html#importing-the-full-article-content

Inserting {{{ content }}} anywhere in the template did not work for some reason but copying the code example of the link worked. 

Thanks!
