### ISSUE TITLE
Omnivore don't support LaTeX/Mathematics?

### ISSUE THREAD

**Issue by TZeLi27** [omnivore-app/obsidian-omnivore#14]
I use omnivore to collect articles from zhihu, but some lines use LaTeX/Mathematics may not support?
![Snipaste_2023-02-03_11-09-12](https://user-images.githubusercontent.com/94706326/216503439-7ce2a619-cef9-4ab1-911e-8f93e66deb45.png)

**Comment by jacksonh** [comment]
Hey, I am going to re-open this issue in https://omnivore.app and track it there, thank you! 

Can you supply the original link? We handle MathJax but this looks like it uses a different math embedding framework

**Comment by jacksonh** [comment]
I'll close this one here, and track over there as its an issue with our reader.
