### ISSUE TITLE
More options for filename

### ISSUE THREAD

**Issue by Chan9390** [omnivore-app/obsidian-omnivore#146]
The plugin currently allows `{{{title}}}`, `{{{dateSaved}}}` and `{{{datePublished}}}` as the filename.

<img width="1034" alt="image" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12944530/c1c8218d-e6fc-4973-99c0-8d96f4ab1760">

Using `{{{title}}}` creates issues when the title are huge or contains uncommon characters. Ex: https://github.com/omnivore-app/obsidian-omnivore/issues/77

Having separate file per article is preferable as it makes search & correlate in Obsidian easier.

I think being able to use `{{{id}}}` (UUID) as filename will be handled well across operating systems. I tried it but `{{{id}}}` doesn't seem to be an option.

**Comment by Chan9390** [comment]
Thanks @sywhb! I see that Omnivore plugin's latest version on Obsidian is still 1.7.1. Will it usually take time for the latest version to reflect there?

**Comment by sywhb** [comment]
> Thanks @sywhb! I see that Omnivore plugin's latest version on Obsidian is still 1.7.1. Will it usually take time for the latest version to reflect there?

Weird. Probably it will take some. I will check again

**Comment by Chan9390** [comment]
Cant find this release yet in Obsidian plugins.. 😕

**Comment by sywhb** [comment]
This is weird. Let me recreate a release

**Comment by sywhb** [comment]
I created a new version 1.8.1 and it is available for upgrade ~

**Comment by Chan9390** [comment]
Thanks! I was able to update to 1.8.1 and test the functionality. 

I confirm that all articles follow `{{id}}.md` format.
