### ISSUE TITLE
I want to add the article yearwise?

### ISSUE THREAD

**Issue by pakosaan** [omnivore-app/obsidian-omnivore#164]
Omnivore/Articles/{{{date:YYYY}}}

I wanted  Omnivore/Articles/2023/

**Comment by sywhb** [comment]
<img width="781" alt="Screenshot 2023-12-08 at 3 28 33 PM" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12963965/f8948d5f-56a8-4a72-972a-b9e7a9740d39">

Hey @pakosaan , you can custom the data format of the date variable in the folder name in the settings
