### ISSUE TITLE
Can we have more selective sync?

### ISSUE THREAD

**Issue by jakemkc** [omnivore-app/obsidian-omnivore#17]
Hi,

I have been an Omnivore user for a month and so far I like it a lot. Because I am an Obsidian user, I really appreciate your efforts for creating a sync plugin.

Concerning how to plugin sync the content, I would like to suggest two improvements:

1) Can we have an extra option to sync just the highlights, instead of both the saved article and the highlights?

2) Can we have an extra option to sync just those annotated highlights (i.e. highlights + annotations)

Obsidian is my 2nd brain and I hope to feed in only the resonated content from the saved articles in Omnivore.

Thanks!

**Comment by thinkdiffw** [comment]
If I understand correctly, this option is already available here, in `General Settings - Filter`, select `import just highlights`.

**Comment by jakemkc** [comment]
I have selected this option but it still sync with full text and highlights.

I just updated to v 1.0.4 of the plugin, removed all the sync notes in Obsidian and re-sync, and still I have full text and highlights, not only highlights..

**Comment by thinkdiffw** [comment]
Just delete some fields in the template
```txt
{{#content}}
{{{content}}}
{{/content}}
```

**Comment by jakemkc** [comment]
Thanks for the suggestion, this hack works!
