### ISSUE TITLE
Highlight import not working in Obsidian

### ISSUE THREAD

**Issue by nmariano9** [omnivore-app/obsidian-omnivore#177]
I have the Obsidian plug-in installed and it used to work perfectly, but my highlights are simply not importing when I run "Sync" anymore. I get the "Fetching articles... Articles fetched" dialogue box, but no highlight notes are created. The "Last sync" time in the plug-in settings updates as well. 

Apologies if this has a straightforward solution, not sure how to troubleshoot any further.

**Comment by samuellando** [comment]
Not sure if this will help, but I had the same issue just now. I reset the "Last Sync" field in the settings and it synced all my articles.

**Comment by nmariano9** [comment]
I was able to fix it by setting Filter to "Advanced" and entering "in:all has:highlights" as the custom query. Shout-out to the Discord.
