### ISSUE TITLE
Failed to fetch articles 

### ISSUE THREAD

**Issue by cyclelou** [omnivore-app/obsidian-omnivore#185]
I am using the plugin on four devices (macbook, PC, iphone, iPad). It is failing to fetch articles now on my phone and PC. I have regenerated my API key but that didn't help. I renamed my Omnivore folder to see if it would download the articles again into a new Omnivore folder but that did not work. I am using the sample advanced template for YAML/properties.

My import template is 👍 # {{{title}}}
#Omnivore

[Read on Omnivore]({{{omnivoreUrl}}})
[Read Original]({{{originalUrl}}})

{{{note}}}
{{/note}}

{{{ content }}}

**Comment by StrollStars** [comment]
@sywhb 我也发现了这个问题，应该是最近一次更新插件后出现，之前一直同步到obsidian没有问题，重新生成API无效。

**Comment by MaryseBucking** [comment]
Same problem here. Yesterday was my last sync and since then it hasn't been able to fetch articles. Performed an update of the plugin, but that changed nothing. Enclosed the log of the developer console.
[obsidian.md-1707075657893.log](https://github.com/omnivore-app/obsidian-omnivore/files/14158055/obsidian.md-1707075657893.log)

**Comment by StrollStars** [comment]
@sywhb @cyclelou @MaryseBucking 我下载了1.9.1版本进行了覆盖，发现还是无法同步，不知道是1.9.2版本更改了个人配置数据，还是服务器那边的问题。

**Comment by StrollStars** [comment]
@cyclelou @MaryseBucking Synchronization has been successful, and the reason for the lack of synchronization seems to be the inconsistency between the server's records and the client's records.

**Comment by sywhb** [comment]
hey guys, sorry for the delay in reply and i'm just back from holiday.

**Comment by sywhb** [comment]
hey @cyclelou , i think you could remove `{{/note}}` from the template as it is used to close a section

**Comment by sywhb** [comment]
hey @StrollStars , 是的，我们把一些数据处理的方式改成了异步，所以插件同步上可能会有一点点延迟

**Comment by sywhb** [comment]
hey @MaryseBucking , i think there might be some invalid characters in the "Custom Query" setting, for example: `label:\"some label\"` needs to be changed to `label:"some label"`

**Comment by StrollStars** [comment]
@sywhb 如何理解同步所有条目和同步高亮条目？如果我有一篇文章没有高亮，如果同步所有条目会把标题同步到本地，而同步高亮条目就不会同步了是吗？

**Comment by sywhb** [comment]
> @sywhb 如何理解同步所有条目和同步高亮条目？如果我有一篇文章没有高亮，如果同步所有条目会把标题同步到本地，而同步高亮条目就不会同步了是吗？ PS：另一个关于知乎的也请麻烦看下。

对的。

好的，我去看一下～
