### ISSUE TITLE
Add "Sync on load" option in settings

### ISSUE THREAD

**Issue by iandelivery** [omnivore-app/obsidian-omnivore#189]
When using git to sync obsidian vault, syncing omnivore on load might cause working directory changes.

I have commented out `await this.fetchOmnivore();` in `async onload()` to prevent syncing on load for now. Of cause adding Omnivore folder to `.gitignore` will do the job too.

**Comment by sywhb** [comment]
hey @iandelivery , i just added this option in v1.9.4

**Comment by sywhb** [comment]
<img width="781" alt="Screenshot 2024-02-20 at 11 19 35 AM" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12963965/ea8767da-f70b-4c32-8138-89f069aece4e">

**Comment by sywhb** [comment]
please let me know if it suits your need

**Comment by iandelivery** [comment]
> please let me know if it suits your need

Sorry for late reply.
It works like a charm!
