### ISSUE TITLE
Can I choose which articles to sync?

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/obsidian-omnivore#19]
Now I can only save or mark specific articles first, or delete the articles that I don't want to sync, and then sync.

**Comment by ltroj** [comment]
Adding to this, setting a ``Custom query`` like ``label:send-to-vault`` has no effect, it still fetches all new articles. Is this a bug or is something wrong with my query? It works in the Omnivore search bar.

**Comment by sywhb** [comment]
Hey @ltroj, may I know if you have selected "Advanced" filter type in the settings? We need it to be selected to make the custom query work.

<img width="666" alt="Screenshot 2023-02-28 at 11 10 34 AM" src="https://user-images.githubusercontent.com/12963965/221743825-1e568d9f-cfae-44a7-bcb1-6300e4e2231f.png">

**Comment by sywhb** [comment]
Hey @StrollStars, this is currently not configurable in the plugin. 

What I'm doing right now is the same as @ltroj. I add the label "sent to obsidian" to the articles in Omnivore. In the plugin, I select "advanced" `Filter` type and set the `Custom query` to `label:"sent to obsidian"` in the settings

**Comment by ltroj** [comment]
> Hey @ltroj, may I know if you have selected "advanced" filter type in the settings? We need it to be selected to make the custom query work.

Thanks, that works!
Those settings aren't really self-explanatory though, maybe these should be labeled different. ``Filter: import all my articles`` and ``Filter: import just highlights`` fetches the same articles it seems? Or do I need to use the ``content`` variable in my template to see the effects?

**Comment by StrollStars** [comment]
> In the plugin, I select "advanced" `Filter` type and set the `Custom query` to `label:"sent to obsidian"` in the settings

Thanks for your help, so can it support multiple conditions?

**Comment by ltroj** [comment]
> Thanks for your help, so can it support multiple conditions?

Yes, please see the [docs](https://omnivore.app/help/search).

**Comment by sywhb** [comment]
Glad to know it works, @ltroj. Yeah, we are working on a doc to guide users on the configuration of the plugin.

`Filter: import all my articles` is to import all the articles with or without highlights and `Filter: import just highlights` is to import articles with highlights that are the results from the search filter: `has:highlights`. These two are a bit confusing and I will rewrite the descriptions

**Comment by StrollStars** [comment]
@ltroj Thanks for your help.

@sywhb Perhaps the setting can be made easier. For example, label, status, type and other options can be provided in the drop-down box, and then followed by the content that the user wants to input, so as to combine a filter.
Going a step further, it supports AND and OR clauses to join multiple combinations.

**Comment by StrollStars** [comment]
@sywhb I agree with you, thank you for your help, it has met my needs so far, closed.

**Comment by GonzOdin** [comment]
> @StrollStars we support AND, OR and NOT clauses in label filters.
> 
> ## Some examples:
> * `label:Newsletter` finds all pages that have the label Newsletter
> * `label:Cooking,Fitness` finds all your pages with either the Cooking or Fitness labels
> * `label:Newsletter label:Surfing` finds all pages with both the Newsletter and Surfing labels
> * `label:Coding -label:News` finds all pages with the Coding label that do not have the News label
> 
> I agree with you it's good to have a UI for such a complex feature. Probably we can add it after the functionality is stablized and we can move on to some enhancements

For clarity, we should express that quotes are to be used when multiple words are used in a label and that it is case sensitive.

Recommend appending to the list of examples.
> ## Some examples:
> * `label:Newsletter` finds all pages that have the label Newsletter
> * `label:Cooking,Fitness` finds all your pages with either the Cooking or Fitness labels
> * `label:Newsletter label:Surfing` finds all pages with both the Newsletter and Surfing labels
> * `label:Coding -label:News` finds all pages with the Coding label that do not have the News label
> * `label:"send to obsidian"` finds all pages with the **send to obsidian** label (mutli-word label)

**Comment by StrollStars** [comment]
@GonzOdin Thank you for your help.
