### ISSUE TITLE
Error: File name cannot contain any of the following characters: \ / :

### ISSUE THREAD

**Issue by oscaromsn** [omnivore-app/obsidian-omnivore#207]
Hey there!

I'm facing the error "Failed to fetch articles". At the console, shows the error "File name cannot contain any of the following characters: \ /". Looking at the line indicated on the right side, it points to the "await this.app.vault.createFolder(folderName);".

I had setup the folder structure "sources/Omnivore/{{{author}}}" and taking a look at my newsletters, actually there's an sender which name uses "/". 

Is there any workaround such rename the sender within Omnivore or maybe setup an replacement for those letters when importing? I don't want to simply delete this sender.

Thank you all — this plugin help me a lot! :)

**Comment by lestertay** [comment]
Hey, I encountered the same issue as you. I believe #211 will be able to fix this!

**Comment by oscaromsn** [comment]
nice - many thanks! :D
