### ISSUE TITLE
[BUG] files not synced into single folder when Folder options set

### ISSUE THREAD

**Issue by ruinshe** [omnivore-app/obsidian-omnivore#219]
Currently the default sync destination is set as `Omnivore/{{{date}}}`, but I found `Omnivore-{{{date}}}` folders created instead of all files begin placed into `Omnivore` folder.

What I want the synced folder looks like:

```
.
├── Omnivore
│   ├── 2024-04-08
│   ├── 2024-04-09
│   ├── 2024-04-10
│   ├── 2024-04-14
│   ├── 2024-04-15
│   └── 2024-04-16
...
```

And actual synced files:

```
.
├── Omnivore-2024-04-08
├── Omnivore-2024-04-09
├── Omnivore-2024-04-10
├── Omnivore-2024-04-14
├── Omnivore-2024-04-15
├── Omnivore-2024-04-16
...
```

**Comment by thatside** [comment]
unfortunately this seems to be caused by https://github.com/omnivore-app/obsidian-omnivore/pull/211 - the fix is replacing forward slash as well as space symbols

**Comment by fpehar** [comment]
After the update, I have the same issue: I can't store the notes in a subfolder

**Comment by Eng4G3** [comment]
I am having the same or similar issue. Installed the Obsidian plugin yesterday with the file path set to:

`03-Resources/Zett`

but when it syncs it is actually creating a new folder and populating it: 03-Resources-Zett

**Comment by sywhb** [comment]
Hey guys, sorry for the mess.

I just released a new version `1.10.1` to fix this bug

@fpehar @ruinshe @thatside @Eng4G3 @StrollStars

**Comment by Tesselay** [comment]
Glad I could help!

**Comment by StrollStars** [comment]
@sywhb Thank you very much!

**Comment by ruinshe** [comment]
Thanks! I upgraded and verified the issue is gone in latest version of Obsidian plugin, closing this issue.
