### ISSUE TITLE
同步文件夹错误

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/obsidian-omnivore#225]
@sywhb 最近的版本更新，造成了同步目录变化。
同步文件夹：`Omnivore/{{{datePublished}}}`
文件夹日期格式：`yyyy`
假如文章发布于2023年，先前的版本会将文章同步到`Omnivore/2023`，这也是我期望的格式，但是最近更新后，文件被同步到了`Omnivore-2023`。
这样造成了我整个目录结构的破坏，好在只同步了最近的文章，影响还不大，可否尽快修复这个问题？

**Comment by StrollStars** [comment]
The same as #219

**Comment by sywhb** [comment]
我 merge 了一个 PR, 但我没仔细看清楚 😢 

感谢 @StrollStars ！我马上修复

**Comment by StrollStars** [comment]
@sywhb 谢谢快速修复，顺带问下之前的知乎回答保存有改进吗？
