### ISSUE TITLE
Multi-line highlights are improperly formatted

### ISSUE THREAD

**Issue by profucius** [omnivore-app/obsidian-omnivore#23]
I have found a possible issue with downloading highlights which span across multiple paragraphs, particularly if they include bullet/number lists.

Example: I am using your "Getting Started With Omnivore" article which is included in a fresh signup to your service.

# Paragraph line with a following list.

## I made a highlight of this text at the top of the article:
![image](https://user-images.githubusercontent.com/18254607/220183053-53aa9377-97b1-408e-afa4-011be09ebcf3.png)

## And the resulting highlight downloaded to my Obsidian vault appears this way:
![image](https://user-images.githubusercontent.com/18254607/220182961-7b2c2049-4a8a-4616-a690-6ab157c9f4ef.png)

As you can see, the formatting for the first line is correct, but the bulleted/numbered list following it is formatted with incorrect tabulations and no `>` (obsidian quote symbol)

---

Another example with a different incorrect format: 
# List only (no leading paragraph line). Same article as above.

## I make a highlight as such:
![image](https://user-images.githubusercontent.com/18254607/220183452-c6b7f60a-d35c-436a-88d6-bb2001ff73fc.png)

## Which is downloaded to Obsidian as such:
![image](https://user-images.githubusercontent.com/18254607/220183518-8a10b984-8751-495e-abbc-3824587a66ce.png)

---

One more example with yet another different incorrect format: 
# Sub-bullet list under a numbered list. Same article as above.

## I make a highlight as such: (note I do not highlight the numbered line)
![image](https://user-images.githubusercontent.com/18254607/220183670-1381d6bc-b0db-4ff9-a488-4ddfc83d76f4.png)

## Which is downloaded to Obsidian as such:
![image](https://user-images.githubusercontent.com/18254607/220183760-7a523c2e-d76a-4f48-bf5d-ac83135d3f1b.png)

---

Template I am using within Obsidian:
```
{{#highlights.length}}
## Highlights

{{#highlights}}
> {{{text}}} [⤴️]({{{highlightUrl}}})
{{#note}}

{{{note}}}
{{/note}}

{{/highlights}}
{{/highlights.length}}
```

**Comment by sywhb** [comment]
Hey @profucius, sorry for the late reply. We have some root issues with saving the multi-line or merged highlights content in Omnivore. I'm trying to retain the format of the highlighted content as it is in the Omnivore API.

Hey @RicSanOP, thanks for the fix! Yeah, I think this should work for most cases. Let me know if you'd like to submit a PR for that or I can create one too

**Comment by RicSanOP** [comment]
Hey @sywhb, sorry to lay this on you, but could you PR it. I don't think this is release worthy. I also haven't cloned/forked the repo. However, I may be interested in collabing on solving the root issue on the backend side that sends the data in such wrong formatting. Happy that an open source and free option read it later app exists.

**Comment by sywhb** [comment]
We are working on creating highlight `quote` in markdown format in Omnivore to retain some of the HTML format including multi-line paragraphs

**Comment by sywhb** [comment]
Hey @profucius @RicSanOP, a new version `1.2.2` is released to address this issue.

Kindly upgrade the plugin and let me know if it works for you
