### ISSUE TITLE
template is not working

### ISSUE THREAD

**Issue by KristineWatson** [omnivore-app/obsidian-omnivore#28]
![图片](https://user-images.githubusercontent.com/92555979/221401446-47585e3b-57e8-42ae-9ed2-02209292376b.png)
![图片](https://user-images.githubusercontent.com/92555979/221401502-84e8629d-fad1-48e7-8396-1f8bae57ccb8.png)

**Comment by sywhb** [comment]
Hey @KristineWatson, thanks for reporting. I'm working on a fix

**Comment by ltroj** [comment]
Came here to ask if it's possible to configure the frontmatter via template. Seems to be the same issue. The original template doesn't contain the frontmatter part at all:

```
# {{{title}}}
#Omnivore

[Read on Omnivore]({{{omnivoreUrl}}})
[Read Original]({{{originalUrl}}})

{{#highlights.length}}
## Highlights

{{#highlights}}
> {{{text}}} [⤴️]({{{highlightUrl}}})
{{#note}}

{{{note}}}
{{/note}}

{{/highlights}}
{{/highlights.length}}
```

**Comment by sywhb** [comment]
We use the `uuid` of the article to deduplicate and it is stored in the frontmatter(YAML) so at least we might need to keep the `uuid` in the frontmatter and remove the others @ltroj @KristineWatson

**Comment by sywhb** [comment]
Something like this:
<img width="663" alt="Screenshot 2023-03-08 at 8 41 53 PM" src="https://user-images.githubusercontent.com/12963965/223716016-c9ab4c67-2a3d-408e-84b3-ba66889943c1.png">

**Comment by sywhb** [comment]
#30

**Comment by ltroj** [comment]
> Something like this: <img alt="Screenshot 2023-03-08 at 8 41 53 PM" width="663" src="https://user-images.githubusercontent.com/12963965/223716016-c9ab4c67-2a3d-408e-84b3-ba66889943c1.png">

I see. Would it be possible to create a custom frontmatter section within the template and you append the ``uuid`` field automatically?

The reason is I use an uniform frontmatter template for all my notes and would like to keep it for notes from Omnivore.

So my template within the plugin settings would look something like this:
```
---
title: {{{title}}}
myCustomField: "Omnivore rocks"
---
# {{{title}}}
#Omnivore
...
```

and when fetching an article it renders like this

```
---
title: "My Article from Omnivore"
myCustomField: "Omnivore rocks"
id: xyz-999
---
# My Article from Omnivore
#Omnivore
...
```

**Comment by sywhb** [comment]
@ltroj thanks for the feedback and "Omnivore rocks" 😄 

Yeah, you could have the frontmatter in the template too.
This is part of my template as an example:
```
---
id: {{{id}}}
title: {{{title}}}
{{#labels.length}}
tags:
{{#labels}} - {{{name}}}
{{/labels}}
{{/labels.length}}
---

# {{{title}}}
#Omnivore
```

**Comment by almabel01** [comment]
Hi @sywhb,
I'm afraid I am a bit dumb for this. When I put the frontmatter in the template in Obsidian, on resync it has been added after the default frontmatter.
My goal is to remove the labels from the fronmatter tags and use wikilinks to the topics.

```
—-
id: {{{id}}}
url: {{{originalUrl}}}
omnivore_url: {{{omnivoreUrl}}}
title: {{{title}}}
author: {{{author}}}
publisher: {{{siteName}}}
date_published: {{{date}}}
tags:
date_saved: {{{dateSaved}}}
—
areas:: {{#labels.length}} {{#labels}}[[{{{name}}}]], {{/labels}}{{/labels.length}}
related notes::

# {{{title}}}

{{#highlights.length}}
## Highlights

{{#highlights}}
> {{{text}}} [⤴️]({{{highlightUrl}}})
{{#note}}

{{{note}}}
{{/note}}

{{/highlights}}
{{/highlights.length}}
```

![Screen Shot 2023-03-08 at 20 01 17](https://user-images.githubusercontent.com/35218668/223812161-955a4d70-beb2-4869-8cd4-0cc085e0e65b.png)
![Screen Shot 2023-03-08 at 20 02 24](https://user-images.githubusercontent.com/35218668/223812305-91035691-c498-400c-9164-4a51323d78eb.png)

**Comment by sywhb** [comment]
Hey @almabel01, sorry for inconvenience caused. This fix is not released yet and I will update you once it's released

**Comment by KristineWatson** [comment]
Got it！Thank you so much for replying ！ It would be nice if it'll supported to set custom frontmatter sections like other plugins in the future😇
________________________________
发件人: Hongbo Wu ***@***.***>
发送时间: 2023年3月7日 16:01
收件人: omnivore-app/obsidian-omnivore ***@***.***>
抄送: KristineWatson ***@***.***>; Mention ***@***.***>
主题: Re: [omnivore-app/obsidian-omnivore] template is not working (Issue #28)


We use the uuid of the article to deduplicate and it is stored in the frontmatter(YAML) so at least we might need to keep the uuid in the frontmatter and remove the others @ltroj<https://github.com/ltroj> @KristineWatson<https://github.com/KristineWatson>

**Comment by sywhb** [comment]
Hey @KristineWatson @ltroj @almabel01, sorry for the long delay. Please check out the new version v1.1.0

I hope it will address the issue here
