### ISSUE TITLE
Feature Request: Customizing options

### ISSUE THREAD

**Issue by johannes1984** [omnivore-app/obsidian-omnivore#31]
Thanks for the great work! :-)

I have two feature requests:
1. Make the frontmatter customizable in the plugin, similar to the template code.
2. Provide an option to a) create a single note for each imported link vs b) have one designated Omnivore note where all links are appened. I know that the id is important and needs to go somewhere, maybe it would be possible for b) to list all id's in the frontmatter like:
```
id:
    - ID1
    - ID2
    - ID3
```
Thanks for considering :-)

**Comment by sywhb** [comment]
Hey @johannes1984, Omnivore plugin 1.3.0 is released.

You can now customise the front matter as well as sync everything into a single note.

I'm looking forward to your feedbacks on the update.

**Comment by johannes1984** [comment]
Many thanks, @sywhb! I‘ll check it out shortly. Although I’m a bit between Obsidian and Logseq at the moment and thinking about what path to go 😊
