### ISSUE TITLE
forward slash in link has been escaped to &#x2F;

### ISSUE THREAD

**Issue by Baoyx007** [omnivore-app/obsidian-omnivore#32]
examples:

```
[https:&#x2F;&#x2F;docker.nju.edu.cn&#x2F;](https:&#x2F;&#x2F;link.zhihu.com&#x2F;?target&#x3D;https%3A&#x2F;&#x2F;docker.nju.edu.cn&#x2F;)
```

**Comment by sywhb** [comment]
Hey @Baoyx007, sorry for the delay in reply.

All variables in the template are HTML-escaped by default. If you want to render unescaped HTML, use the triple mustache: `{{{name}}}`. You can also use `&` to unescape a variable.

So for your example, you could use`[{{{originalUrl}}}]` in your template to unescape the URL when rendering
