### ISSUE TITLE
The issue of creating another file when modifying an article and syncing it again.

### ISSUE THREAD

**Issue by YIRU69** [omnivore-app/obsidian-omnivore#33]
First of all, I appreciate your contribution. However, I encountered a troublesome issue while attempting to use this plugin. Upon my initial synchronization, Article A was successfully synced to Obsidian. However, when I tried syncing it again, there was no response. Only when I made changes like modifying the title, adding or changing highlights, or adding tags, did a new synchronized file appear in Obsidian. This is clearly illogical. What I expect is that upon synchronization, there should be only one corresponding article between Obsidian and Omnivore. If I make any modifications in Omnivore, they should also reflect in Obsidian after synchronization, instead of creating a new file.

**Comment by YIRU69** [comment]
I have identified the issue at hand. I have modified the value of "id". Is it possible to judge based on the filename? Could there be an option made available to choose between utilizing the id or the title for the judgment? If feasible, I can accept either choice at your discretion.

**Comment by sywhb** [comment]
Hey @YIRU69 , sorry for the delay. As there could be some articles with the same `title` so it is hard to deduplicate them based on the `title`.

We have to use the `id` to locate the exiting article in the vault so I will probably close this issue for now.
