### ISSUE TITLE
FR: Get description in template

### ISSUE THREAD

**Issue by skyue** [omnivore-app/obsidian-omnivore#34]
I use description to summarize/comment article. It is good if add description in template?

<img width="449" alt="image" src="https://user-images.githubusercontent.com/10450242/226090272-bb1456ac-dbb8-4189-aa0b-79c5e9d26e6c.png">

**Comment by sywhb** [comment]
#41

**Comment by sywhb** [comment]
Hey @skyue, we have added `description` in the template in the latest release
