### ISSUE TITLE
Importing highlights labels escapes slash character

### ISSUE THREAD

**Issue by dbobak** [omnivore-app/obsidian-omnivore#40]
New feature in 1.1.1 is possibility to import labels of individual higlights (as requested in #22 and #35). But when the label contains slash character (`/`), it is escaped, which in result makes it wrongly import into Obsidian. The same tags are correctly imported into yaml frontmatter, the problem is only with labels attached to specific highlights in note body:

![image](https://user-images.githubusercontent.com/6285546/229090281-102d2a91-d91d-45ef-a910-746471b56afb.png)

**Comment by sywhb** [comment]
Hey @dbobak, all variables in the template are HTML-escaped by default. If you want to render unescaped HTML, use the triple mustache: {{{name}}}. You can also use `&` to unescape a variable.

For instance, to show the slash correctly in the label names, I use this template:
```
{{#labels}} #{{{name}}} {{/labels}}
```

As a result, I can get something like this:
<img width="689" alt="Screenshot 2023-04-03 at 6 11 09 PM" src="https://user-images.githubusercontent.com/12963965/229480232-efeaaef5-3074-4c7d-9726-1b6344a15fac.png">
