### ISSUE TITLE
Allow syncing full article, not just highlights

### ISSUE THREAD

**Issue by samwho** [omnivore-app/obsidian-omnivore#43]
I have a use-case where having full article content synced to my vault would be fantastically useful. Is this something the project would consider adding? I'd be happy to take a swing at implementing it.

**Comment by sywhb** [comment]
Hey @samwho, you can use `content` variable in your template to import the article content.

For instance:
```
## Content
{{content}}
```

**Comment by samwho** [comment]
Oh my gosh, I completely missed that. Thank you so much.

**Comment by samwho** [comment]
Hmm, the content appears to have escaping.

I have synced the article https://www.bowtie.works/blog/baking-images-with-nix-for-robust-private-networks-at-bowtie and in the article we have this code block:

<img width="776" alt="image" src="https://user-images.githubusercontent.com/338027/231722806-1a5b5d70-0f2b-4173-bb8a-fdef6b8c3963.png">

Which appears as this in Obsidian:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/338027/231722885-6f0dc02b-63c7-4fde-9331-fd18d7f77249.png">

**Comment by samwho** [comment]
A-ha! Using `{{&content}}` removes the escaping. Hopefully this helps others who stumble upon this. :)
