### ISSUE TITLE
The "Folder" and "Attachments folder" setup is not respected if updated after the sync

### ISSUE THREAD

**Issue by david-vaclavek** [omnivore-app/obsidian-omnivore#47]
This is probably only a one-timer for a user, but technically it is a bug.

## Problem

The "Folder" and "Attachments folder" setup is not respected if updated after the sync.

## Replication

I let Omnivore Plugin sync the notes to the default folder (just to test it out).
After that, I updated the folders in the settings. Then, during the next sync, this setup was not respected.

## Desired behavior

Sync should respect the updated settings.

## Resolution

I've currently resolved it by uninstalling and installing the plugin again and settings up the correct folders in the General Settings before the actual 1st sync.

**Comment by sywhb** [comment]
Hey @david-vaclavek , thanks for the patience and we have fixed this bug in 1.3.0 release.

Please let me know if it works for you
