### ISSUE TITLE
A feature advise

### ISSUE THREAD

**Issue by Nadir-Echo** [omnivore-app/obsidian-omnivore#48]
I feel that this plugin is used with omnivore, which is very good!
In addition, I would like to ask, have you considered exporting the whole article to obsidian, importing the comment part with css style, and the note can be displayed at the bottom

**Comment by sywhb** [comment]
Hey @Nadir-Echo, you can use `{{{content}}}` in your template to export the whole article in markdown format

**Comment by jacksonh** [comment]
I am going to close this one as I think it has been addressed, please let us know if you still have issues @Nadir-Echo
