### ISSUE TITLE
Dates - proper date format

### ISSUE THREAD

**Issue by ms3056** [omnivore-app/obsidian-omnivore#51]
In order to query dates in Dataview and sort them the dates need to be proper format. I am writing queries in Dataview to sort and group the articles. 

Current: 2022-11-16 19:17:43

Can you consider bringing the Saved and Published dates in the following format? 

Desired: 2022-11-16T19:17:43

**Comment by sywhb** [comment]
Hey @ms3056, you can use `yyyy-MM-dd'T'HH:mm:ss` as the date saved format in the plugin settings

![](https://cdn.discordapp.com/attachments/1084693944861982791/1100596970902523954/Screenshot_2023-04-26_at_9.39.21_AM.png)
