### ISSUE TITLE
[Bug] General Notes Section

### ISSUE THREAD

**Issue by m4mazzotti** [omnivore-app/obsidian-omnivore#59]
I am trying to use the following template to include a general notes header (not the highlight notes) only when there are notes, however it doesn't seem to be working, the header is always there.
`{{# section }} ... {{/ section }}: Renders a section of the template if the value of the section is true, such as an array or an object.`

Code:
```
[Read Original]({{{originalUrl}}})
{{#note}}
## General Notes
- {{{note}}}
{{/note}}
```

Update: After further testing, I have identified that if you have never added a note to an article, it works, however, if you added a note and then removed it, {{#note}} will `return true`.

**Comment by jacksonh** [comment]
Thanks, i think in this case the note can get set to an empty string. Can i ask which app you are using to remove the note? iOS?

**Comment by m4mazzotti** [comment]
I think it was my fault, I didn't wait enough time for it to save after I removed the a empty space I left there. I just gave it another go and it is working as it should.
