### ISSUE TITLE
Not syncing at all.. no way to force sync?

### ISSUE THREAD

**Issue by jasmeetchadha** [omnivore-app/obsidian-omnivore#61]

**Comment by sywhb** [comment]
Hey @jasmeetchadha , you could press Command/Control + P on the keyboard in Obsidian to get the command palette and search for "resync".

Clicking on the "Omnivore: Resync all articles" will do the job.
<img width="701" alt="Screenshot 2023-05-11 at 6 14 33 PM" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12963965/b82fd3d3-b242-4852-b722-247f2d8ac1ae">
