### ISSUE TITLE
Appending all Highlights in a single page instead of creating a new page for each Article

### ISSUE THREAD

**Issue by kngautham** [omnivore-app/obsidian-omnivore#63]
Please give us the option to Append Highlights from all articles to a single Page(One can choose the page in the settings)

Will be helpful
Thanks

**Comment by sywhb** [comment]
Hey @kngautham , we have added this feature in `1.3.2` release.

<img width="695" alt="Screenshot 2023-05-23 at 12 28 40 PM" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12963965/4e80661b-9946-4638-ab22-94d3bd546261">

You can turn it on by enabling "IsSinglePage" toggle and set a fixed "Filename" in the plugin settings.

Please try it out!

**Comment by kngautham** [comment]
Perfect. Thank you so much
