### ISSUE TITLE
Tags coming in strange

### ISSUE THREAD

**Issue by ms3056** [omnivore-app/obsidian-omnivore#69]
It looks like tags are now coming in like this:

tags:
    - name: tag1
    - name: tag2
    - name: tag3
    
 Why? I would like this, or, I would like to control it as before:
 
 tags: [tag1, tag2, tag3]
 
 or 
 
 tags:
    - tag1
    - tag2
    - tag3

**Comment by ms3056** [comment]
1.3.2 addresses this issue - thank you!

**Comment by sywhb** [comment]
@ms3056 thank you and welcome for the feedback!
