### ISSUE TITLE
Metadata synchronization problem

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/obsidian-omnivore#72]
![template](https://github.com/omnivore-app/obsidian-omnivore/assets/10942225/5a859bee-77d1-4743-96d0-840771e268c3)
![result](https://github.com/omnivore-app/obsidian-omnivore/assets/10942225/2e772937-6173-4bcb-b50f-09ff0e5195a5)
Comparing two images, there are 3 synchronous problems:
1. tags: Why can't "Omnivore" appear?
2. tags: Why do the tags have a hyphen before the line break?
3. datePublished: Why can't it be synchronized?

**Comment by rmateu** [comment]
Same thing happened to me, I was using a custom metadata within the file template. However, version 1.3 moved all YAML to _Front Matter Variables_.

<img width="399" alt="image" src="https://github.com/omnivore-app/obsidian-omnivore/assets/879149/6a87302d-b63b-4a72-8d92-f9bedf80447a">

I can see how this would be simpler for some users – and can probably guess that some were messing with `id:` which affected the sync. However, this throws a wrench at my current workflow in obsidian, since I relied on my custom attributes.

**Comment by mwisnefsky** [comment]
Not sure if this is the same thing or not.  I attempted to add a "Reviewed: false" line to the YAML template but it's not using it.
![image](https://github.com/omnivore-app/obsidian-omnivore/assets/19543792/4f99995c-add8-45b5-9cb8-f6979907aa09)

**Comment by StrollStars** [comment]
@mwisnefsky [Variables available in the template](https://docs.omnivore.app/integrations/obsidian.html#variables-available-in-the-template)

**Comment by mwisnefsky** [comment]
> @mwisnefsky [Variables available in the template](https://docs.omnivore.app/integrations/obsidian.html#variables-available-in-the-template)

Ah - my bad, didn't realize it stripped out YAML that didn't match the predefined ones.

**Comment by sywhb** [comment]
Hey guys, **Omnivore plugin 1.4.0** is out.

I hope it will solve all the issues with parsing YAML in the front matter and the sync will continue even if there was a parsing error.

Additionally, now you can create an alias for the metadata in the front matter in the format of `metadata::alias`. For example, `state::status` will create a metadata `status` to represent the `state`. The available metadata could be found [here](https://docs.omnivore.app/integrations/obsidian.html#front-matter).

Screenshot:
<img width="680" alt="Screenshot 2023-05-31 at 4 56 05 PM" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12963965/494919c3-2386-4d88-be70-d20129acf1cf">

Moreover, for users with the need to put hardcoded metadata in the front matter or some other advanced usage, we have added a "front matter template" section under the advanced settings. It will be override the "Front matter" if set. Sample template could be found [here](https://docs.omnivore.app/integrations/obsidian.html#front-matter-template).

Screenshot:
<img width="681" alt="Screenshot 2023-05-31 at 4 56 17 PM" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12963965/5889176a-611d-481e-bc17-43e8aec9e4f5">

**Comment by StrollStars** [comment]
@sywhb My question has been resolved. Thank you, developers.
