### ISSUE TITLE
I can't find the Omnivore icon on the ribbon

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/obsidian-omnivore#9]
The second point of [usage](https://github.com/omnivore-app/obsidian-omnivore/blob/master/README.md#usage):
> You can also manually sync with Omnivore by clicking the Omnivore icon on the ribbon

But i can't find the icon.
![2023-01-21_125343](https://user-images.githubusercontent.com/10942225/213844100-9bf49741-c35b-4539-9653-d85f6bd445e3.png)

**Comment by Mahaprasad003** [comment]
Were you able to find the plugin in the community plugin tab?

I can't seem to find it.

![image](https://user-images.githubusercontent.com/64512697/213873695-0e17d9ae-c72a-44a7-8cd8-c167e77166a3.png)

**Comment by StrollStars** [comment]
@Mahaprasad003 I download from [here](https://github.com/omnivore-app/obsidian-omnivore/releases).

**Comment by Mahaprasad003** [comment]
Thanks, StrollStars.
I have the same problem too.

Another problem is it synced the entire article to my Obsidian instead of just the highlights. Did the same happen with you too?

**Comment by StrollStars** [comment]
Solved with the Commander plugin.

**Comment by sywhb** [comment]
Hey @StrollStars, sorry, we removed the icon because of some feedback but didn't update the README properly.

May I know if you prefer to have the icon on the ribbon?

**Comment by sywhb** [comment]
Hey @Mahaprasad003, we are still waiting for the approval of our plugin in the community market and so far you could download the plugin manually in the releases

**Comment by Mahaprasad003** [comment]
Hey. Thanks.
Downloaded it and it's working fantastic.

While it's not a big issue, a ribbon icon (optional) will definitely be a helpful feature.

**Comment by StrollStars** [comment]
@sywhb Yes, the icon on the ribbon helps me sync more easily without having to type commands.

**Comment by sywhb** [comment]
@StrollStars @Mahaprasad003 Appreciate the feedback. I will add the ribbon icon back

**Comment by sywhb** [comment]
Hey @StrollStars, @Mahaprasad003, the icon has been added in version [1.0.2](https://github.com/omnivore-app/obsidian-omnivore/releases/tag/1.0.2)

Feel free to download and try. Let me know if there is anything missing

**Comment by StrollStars** [comment]
@sywhb The function of this button is the same as the command of `Omnivore: Sync`?

**Comment by sywhb** [comment]
@StrollStars yeah, it is used to sync Omnivore data

**Comment by StrollStars** [comment]
@sywhb Sorry, because there is another command in the command is `Omnivore: Resync all articles`, so I asked the above question. 
From the results of my test, as I understand it.

**Comment by StrollStars** [comment]
@sywhb Thank you for your prompt reply, I will open a new issue if there is a new question.

**Comment by Mahaprasad003** [comment]
Thanks a lot @sywhb! Appreciate you implementing the feature!
