### ISSUE TITLE
Bug when importing PDF to Obsidian.

### ISSUE THREAD

**Issue by DudeThatsErin** [omnivore-app/obsidian-omnivore#99]
I would expect to see a copy of the PDF saved to Obsidian and not the information from the PDF copied to Obsidian. It looks ridiculous lol

![image](https://github.com/omnivore-app/omnivore/assets/2681022/9aeb5286-cac1-439b-945e-7c8f5dc24ac5)

This screenshot shows exactly what I am seeing on my iPad.

**Comment by andresrinivasan** [comment]
I expected

```
{{#fileAttachment}}
![[{{{fileAttachment}}}]]
{{/fileAttachment}}

{{^fileAttachment}}
{{{content}}}
{{/fileAttachment}}
```

to accomplish the above.

`{#fileAttachment}...` works as expected and only renders fileAttachment for FILE content.

`{^fileAttachment}...` does not render the content when fileAttachment is false.

**Comment by sywhb** [comment]
I have created a PR #137 so that we will return `content` as `undefined` if we are syncing a PDF @jacksonh
